#!/usr/bin/python

import sys
import locale
import traceback
from PyQt4.QtCore import *
from PyQt4.QtGui import *

from pyqtrailer.main import PyTrailerWidget
from pyqtrailer.logger import log, setup_log

if __name__ == "__main__":
    try:
        setup_log()
        app = QApplication(sys.argv)
        translator = QTranslator(app)
        translator.load("%s.qm" % locale.getlocale()[0],
                        "/usr/share/pyqtrailer/lang/")
        app.installTranslator(translator)
        widget = PyTrailerWidget()
        widget.resize(800, 600)
        widget.show()
        sys.exit(app.exec_())
    except Exception as e:
        log.error("uncaught exception ocurred. Please report this!")
        log.error(traceback.format_exc())
        raise
