#!/usr/bin/python

import sys
import locale
from PyQt4.QtCore import *
from PyQt4.QtGui import *

from pyqtrailer.main import PyTrailerWidget

if __name__ == "__main__":
    app = QApplication(sys.argv)
    translator = QTranslator(app)
    translator.load("%s.qm" % locale.getlocale()[0],
                    "/usr/share/pyqtrailer/lang/")
    app.installTranslator(translator)
    widget = PyTrailerWidget()
    widget.resize(800, 600)
    widget.show()
    sys.exit(app.exec_())
